version: v2

clean: true

inputs:
  - git_repo: https://github.com/cosmos/cosmos-sdk.git
    tag: v0.53.4
    subdir: proto
    exclude_paths:
      - cosmos/benchmark/module/v1
      - cosmos/benchmark/v1
      - cosmos/counter/module/v1
      - cosmos/counter/v1
      - cosmos/protocolpool/module/v1
      - cosmos/protocolpool/v1
      - cosmos/epochs/module/v1
      - cosmos/epochs/v1beta1
      - cosmos/base/reflection/v1beta1
      - cosmos/base/reflection/v2alpha1
      - cosmos/circuit/module/v1
      - cosmos/circuit/v1
      - cosmos/group/module/v1
      - cosmos/group/v1
      - cosmos/params/module/v1
      - cosmos/params/v1beta1
      - cosmos/crisis/module/v1
      - cosmos/crisis/v1beta1
      - cosmos/nft/module/v1
      - cosmos/nft/v1beta1
plugins:
  - remote: buf.build/community/google-gnostic-openapi:v0.7.1
    out: ./gen/cosmos
    include_imports: true
    opt:
      - default_response=true
      - fq_schema_naming=false
      - title=REST API
      - version=v1.0.0
      - Mcosmos/app/v1alpha1/module.proto=cosmossdk.io/api/cosmos/app/v1alpha1
      - Mcosmos/app/v1alpha1/config.proto=cosmossdk.io/api/cosmos/app/v1alpha1
      - Mcosmos/app/v1alpha1/query.proto=cosmossdk.io/api/cosmos/app/v1alpha1
      - Mcosmos/app/runtime/v1alpha1/module.proto=cosmossdk.io/api/cosmos/app/runtime/v1alpha1
      - Mcosmos/auth/module/v1/module.proto=cosmossdk.io/api/cosmos/auth/module/v1
      - Mcosmos/authz/module/v1/module.proto=cosmossdk.io/api/cosmos/authz/module/v1
      - Mcosmos/bank/module/v1/module.proto=cosmossdk.io/api/cosmos/bank/module/v1
      - Mcosmos/gov/module/v1/module.proto=cosmossdk.io/api/cosmos/gov/module/v1
      - Mcosmos/mint/module/v1/module.proto=cosmossdk.io/api/cosmos/mint/module/v1
      - Mcosmos/consensus/module/v1/module.proto=cosmossdk.io/api/cosmos/consensus/module/v1
      - Mcosmos/distribution/module/v1/module.proto=cosmossdk.io/api/cosmos/distribution/module/v1
      - Mcosmos/evidence/module/v1/module.proto=cosmossdk.io/api/cosmos/evidence/module/v1
      - Mcosmos/feegrant/module/v1/module.proto=cosmossdk.io/api/cosmos/feegrant/module/v1
      - Mcosmos/genutil/module/v1/module.proto=cosmossdk.io/api/cosmos/genutil/module/v1
      - Mcosmos/msg/textual/v1/textual.proto=cosmossdk.io/api/cosmos/msg/textual/v1
      - Mcosmos/orm/module/v1alpha1/module.proto=cosmossdk.io/api/cosmos/orm/module/v1alpha1
      - Mcosmos/orm/query/v1alpha1/query.proto=cosmossdk.io/api/cosmos/orm/query/v1alpha1
      - Mcosmos/orm/v1/orm.proto=cosmossdk.io/api/cosmos/orm/v1
      - Mcosmos/orm/v1alpha1/schema.proto=cosmossdk.io/api/cosmos/orm/v1alpha1
      - Mcosmos/reflection/v1/reflection.proto=cosmossdk.io/api/cosmos/reflection/v1
      - Mcosmos/slashing/module/v1/module.proto=cosmossdk.io/api/cosmos/slashing/module/v1
      - Mcosmos/staking/module/v1/module.proto=cosmossdk.io/api/cosmos/staking/module/v1
      - Mcosmos/tx/config/v1/config.proto=cosmossdk.io/api/cosmos/tx/config/v1
      - Mcosmos/upgrade/module/v1/module.proto=cosmossdk.io/api/cosmos/upgrade/module/v1
      - Mcosmos/vesting/module/v1/module.proto=cosmossdk.io/api/cosmos/vesting/module/v1
