version: v2

clean: true

inputs:
  - directory: .

plugins:
  - remote: buf.build/community/google-gnostic-openapi:v0.7.1
    out: ./gen/
    include_imports: true
    opt:
      - default_response=true
      - fq_schema_naming=false
      - title=REST API
      - version=v1.0.0
      - Mdigitalkitchen/vrf/module/v1/module.proto=github.com/dgtlkitchen/vrf/api/digitalkitchen/vrf/module/v1
